"""Content for the four focused service pages. Imported by build.py."""

# Each page: slug, nav label, title tag, meta description, label, h1, lead,
# problem (heading, paragraphs), build (heading, intro, items), fit (heading, items),
# example (label, heading, paragraphs, facts, link), faq [(q, a)], related slugs.

PAGES = [
    {
        "slug": "iphone-app-development.html",
        "short": "iPhone apps",
        "title": "iPhone App Development in Tampa | Fintlock",
        "description": "Native iPhone apps designed and built in Swift by a Tampa studio, from the first sketch to the App Store. Fixed scope, working builds to review, and code you own.",
        "label": "iPhone app development",
        "h1": "A native iPhone app, built <em>properly.</em>",
        "lead": "Fintlock designs and builds iPhone apps in Swift and SwiftUI, then carries them through TestFlight and App Store review. The whole app, not a website in a wrapper.",
        "problem": ("Why native, and why it matters",
            ["Most business owners come to us with the same worry: they have seen apps that feel slow, look borrowed, and get rejected by Apple, and they do not want to pay for one of those. The cause is usually the same. The app was built as a web page inside a shell, or by a team that had never shipped through App Store review.",
             "A native app uses the phone the way Apple intended. It opens instantly, works offline where it should, uses the camera, notifications, and Face ID directly, and looks at home next to the apps your customers already trust. It is also what Apple's reviewers expect to see."]),
        "build": ("What an iPhone project includes",
            "Every engagement covers the full path from idea to a listing on the App Store. Depending on the product, that means:",
            ["Product planning: working out the few screens that matter and cutting the rest",
             "Interface design in Apple's own conventions, so the app feels familiar on day one",
             "Native development in Swift and SwiftUI, with SwiftData or a backend where the product needs one",
             "Subscriptions and one-time purchases through StoreKit, if the app is a product",
             "Camera, location, notifications, and sign-in with Apple where they earn their place",
             "TestFlight builds for your own testers before anything is public",
             "The App Store listing, screenshots, privacy labels, and review submission",
             "Updates for each autumn's iOS release, so the app keeps working"]),
        "fit": ("A good fit if",
            ["You have a product idea for consumers or professionals and want it done once, well",
             "Your business needs a field app: capture, lookup, checklists, or photos from a job site",
             "You already have an app that is slow, unmaintained, or stuck in review and want it rebuilt",
             "You want a working build on your own phone every step of the way, not a slide deck about one"]),
        "example": ("Project example / Fintley", "Any address, appraised in seconds.",
            ["Fintley is our own real estate app for iPhone. Type an address and it returns an estimated value and range, projected rent, cap rate, monthly cash flow, and a Forecast score from 1 to 100, with a plain-language read on the deal. A Deal Lab lets you change the assumptions and watch the numbers move.",
             "It is built entirely in SwiftUI and is the clearest public example of how we handle data-heavy screens, charts, and a subscription on iPhone."],
            [("Platform", "iPhone"), ("Built with", "SwiftUI"), ("Website", "fintley.app")],
            ("work.html#fintley", "See Fintley")),
        "faq": [
            ("How long does an iPhone app take to build?", "A focused first version usually takes a few months from kickoff to App Store submission. Complex products take longer. We tell you where yours lands after the first conversation, and the written scope fixes it."),
            ("What does an iPhone app cost?", "It depends on what the app has to do, which is why we write the scope down first. You get a price before any code is written, and it does not move unless the scope does."),
            ("Do you build for Android too?", "Our native work is iPhone. If you need both platforms, we will say so up front and talk through the options, including a browser app that works on any phone."),
            ("Who owns the app?", "You do. The source code, the App Store listing, and the developer account are set up in your name."),
        ],
        "related": ["custom-app-development.html", "web-app-development.html", "custom-business-software.html"],
        "schema_name": "iPhone app development",
        "topic": "iPhone apps",
        "blurb": "Native Swift apps, from the first sketch to the App Store.",
    },
    {
        "slug": "custom-business-software.html",
        "short": "Business software",
        "title": "Custom Business Software Development in Tampa | Fintlock",
        "description": "Internal software for the work that has outgrown spreadsheets: quoting, spec checking, reporting, and document workflows. Built around how your company already runs.",
        "label": "Custom business software",
        "h1": "Software for the work that outgrew the <em>spreadsheet.</em>",
        "lead": "Fintlock builds the internal tools a company runs on: quoting, spec checking, reporting, document generation, and the connections between systems that people are still bridging by hand.",
        "problem": ("The problem is usually a process, not a program",
            ["It starts as a spreadsheet someone clever built. Then a second one. Then a shared folder of them, a few macros nobody dares touch, and a person who is the only one who knows how it all fits together. Orders get retyped from one system into another. Someone checks specifications against a catalogue line by line. Reports take a day to assemble because the numbers live in three places.",
             "Off-the-shelf software rarely fixes this, because the process it is meant to support is specific to your company. What fixes it is a small, purpose-built tool that does exactly that job, on the hardware you already have, and is simple enough to hand to a new hire."]),
        "build": ("What we build",
            "We build desktop programs for Windows and Mac, browser-based internal tools, and integrations, depending on where the work happens. Typical projects:",
            ["Quoting and estimating tools that pull prices and rules from your own data",
             "Specification checking against product catalogues, manufacturer data, and job requirements",
             "Document generation: proposals, submittals, reports, and certificates from one set of inputs",
             "Reporting that gathers accounting, sales, and operations figures into one screen",
             "Integrations between the systems you already pay for, so nothing is retyped",
             "Replacing a critical spreadsheet with something several people can use at once without breaking it"]),
        "fit": ("A good fit if",
            ["A key process depends on one person and one spreadsheet",
             "Staff spend hours a week copying information between systems",
             "You have tried off-the-shelf software and ended up working around it",
             "You want a tool your team can run on the computers already on their desks"]),
        "example": ("Project example / Building materials", "Checking specifications without the line-by-line.",
            ["A building materials supplier was checking product specifications by hand: someone would open the job requirements, the product data, and the order, and compare them line by line. It was slow, it depended on a few experienced people, and a miss was expensive.",
             "We built a spec-check tool around the way that work was already done. It takes the requirements and the products in question, flags what does not match, and produces a record the team can send on. The people who did the checking by hand were in the room for every review, which is why it fit on the first day.",
             "We keep client work private, so this is described in general terms. We are happy to walk through it in a conversation."],
            [("Type", "Internal tool"), ("Industry", "Building materials"), ("Status", "In daily use")],
            ("contact.html", "Ask us about it")),
        "faq": [
            ("Desktop program or browser tool: which do we need?", "If the work happens at a few fixed desks with local files, a Windows or Mac program is often simpler and faster. If several people in different places need it, or it has to run on phones, we build it for the browser. We will recommend one after seeing the process."),
            ("Will it work with the software we already use?", "Usually, yes. Most modern systems, from accounting to CRM to supplier portals, have a way to read and write data. Connecting them is a large part of what we do."),
            ("What happens when we need a change later?", "The code is yours and documented. We can stay on for updates, or hand it to your own people. Either way, a small tool built for one process is much easier to change than a big platform."),
            ("Do you work outside construction and building materials?", "Yes. That is where we have the most depth, but the same approach applies to any company with a process that has outgrown its spreadsheet."),
        ],
        "related": ["web-app-development.html", "custom-app-development.html", "iphone-app-development.html"],
        "schema_name": "Custom business software development",
        "topic": "business software",
        "blurb": "Quoting, spec checking, reporting, and the tools a company runs on.",
    },
    {
        "slug": "web-app-development.html",
        "short": "Web apps",
        "title": "Web App Development and Integrations, Tampa | Fintlock",
        "description": "Customer portals, internal browser tools, and integrations between the systems you already use. Built for the browser, so there is nothing to install.",
        "label": "Web app development",
        "h1": "Browser software your customers and team can use <em>anywhere.</em>",
        "lead": "Fintlock builds web apps for businesses: customer portals, internal tools, and the integrations that move data between systems without anyone copying and pasting.",
        "problem": ("When the browser is the right place",
            ["Some software has to run everywhere: on the office desktop, on a phone at a job site, and on a customer's laptop at home. A web app needs no installation, is always the current version, and works on whatever device the person happens to have.",
             "The catch is that a web app is only as good as the plumbing behind it. A portal that shows stale order status, or an internal tool that needs a spreadsheet export every morning, has not solved the problem. We build the connections first and the screens second."]),
        "build": ("What we build",
            "Browser software with a proper backend, hosted on infrastructure in your name. Typical projects:",
            ["Customer portals: order status, documents, invoices, and requests in one place",
             "Internal tools that replace the shared spreadsheet and let several people work at once",
             "Integrations between accounting, CRM, inventory, and field systems",
             "Dashboards that show the numbers people actually check, drawn from live data",
             "Workflow automation: approvals, notifications, and hand-offs that used to travel by email",
             "The web companion to an iPhone app, sharing the same accounts and data"]),
        "fit": ("A good fit if",
            ["Customers keep calling to ask about things they could look up themselves",
             "Your team works from several locations or from the field",
             "Two or more systems hold the same information and someone keeps them in sync by hand",
             "You want software that updates in one place and never needs installing"]),
        "example": ("Project example / Fintley", "A data-heavy product, backed by a real service.",
            ["Fintley, our real estate appraisal app, is an iPhone product on the surface, but everything it shows comes from a service we built and run: property data, valuation, market figures, and the accounts and subscriptions behind them.",
             "It is a useful picture of how we approach web work: the backend is designed to serve more than one front end, so a browser version can share the same data and logins as the phone app."],
            [("Front end", "iPhone"), ("Backend", "Custom service"), ("Website", "fintley.app")],
            ("work.html#fintley", "See Fintley")),
        "faq": [
            ("Where does the web app run?", "On hosting set up in your name, sized to what the app needs. You pay the provider directly and hold the keys; we do the setup and keep it healthy."),
            ("Can it connect to our existing systems?", "Almost always. Accounting packages, CRMs, inventory systems, and supplier portals expose data through APIs or exports, and connecting to them is a core part of the work."),
            ("Will it work on phones?", "Yes. Everything we build for the browser is designed for phones and tablets as well as desktops. If the phone experience needs the camera, offline use, or notifications, we may suggest a native iPhone app alongside it."),
            ("Who owns the code and the data?", "You do. Source code, hosting accounts, and data are all yours from the start."),
        ],
        "related": ["custom-business-software.html", "iphone-app-development.html", "custom-app-development.html"],
        "schema_name": "Web application development",
        "topic": "web apps",
        "blurb": "Portals, internal tools, and integrations, with nothing to install.",
    },
    {
        "slug": "custom-app-development.html",
        "short": "Custom apps",
        "title": "Custom App Development in Tampa, Florida | Fintlock",
        "description": "A Tampa software studio that designs and builds custom apps for businesses: native iPhone apps, browser apps, and the software behind them. Written scope, fixed price, code you own.",
        "label": "Custom app development",
        "h1": "An app built around your business, not a <em>template.</em>",
        "lead": "Fintlock designs and builds custom apps for companies that need something specific: a product for customers, a tool for the team, or both, on iPhone and in the browser.",
        "problem": ("What custom means here",
            ["Plenty of companies can build an app. Fewer will sit with the people who do the work, understand the day-to-day operation, and build the app around it rather than around a template. That is the difference between software people use and software people work around.",
             "Custom does not mean complicated. The best apps we build do a small number of things exactly right for one company. The scope is written down, the price is fixed against it, and you see working builds as it comes together rather than waiting for a reveal."]),
        "build": ("What a custom app project includes",
            "We handle the whole thing in-house, from the first conversation to launch and after. A typical project covers:",
            ["A short discovery phase with the people who will use the app, not only the people paying for it",
             "Interface design in the conventions of the platform, so nothing needs explaining",
             "Native iPhone development in Swift, browser development with a proper backend, or both sharing one service",
             "Accounts, payments, notifications, and integrations as the product needs them",
             "Working builds on your own devices throughout, and a written scope that fixes the price",
             "Launch through the App Store or your own hosting, then documentation and a clean handover"]),
        "fit": ("A good fit if",
            ["You are a business owner with a product idea and want one team that can design, build, and ship it",
             "You need an app for your customers and a tool for your staff, and want them to share the same data",
             "You have been quoted a big-agency price and a big-agency process and want something more direct",
             "You would like to talk to the people writing the code, not an account manager"]),
        "example": ("Project example / Plants in Pocket", "Identify a plant, then keep it alive.",
            ["Plants in Pocket is our own consumer app for iPhone. Identify a plant, check its health, and follow a care plan written for that plant. Most plant apps stop at the name; this one goes on to the part that matters: what should I do this week?",
             "It shows the full arc of a custom app project: an idea, a focused feature set, interface design, native development, and an App Store launch, all done by one small team."],
            [("Platform", "iPhone"), ("Category", "Plant care"), ("Status", "Available now")],
            ("https://apps.apple.com/us/app/plants-in-pocket-plant-id/id6790838495", "View on the App Store")),
        "faq": [
            ("iPhone app or web app: which should we build?", "If the app needs the camera, offline use, notifications, or a place on someone's home screen, native iPhone. If it needs to run on any device with nothing to install, the browser. Many products need both, sharing one backend, and we build those too."),
            ("How do you price a project?", "Against a written scope. After the first conversation we send a scope and a price. The price holds unless the scope changes, and you decide when it does."),
            ("Do we need a detailed brief to start?", "No. A few sentences about what happens today, who is involved, and what you want to change is enough. We do the rest of the discovery with you."),
            ("What happens after launch?", "We can stay on for updates, new features, and the yearly round of operating system changes, or hand everything over to your team. The code and the accounts are yours either way."),
        ],
        "related": ["iphone-app-development.html", "web-app-development.html", "custom-business-software.html"],
        "schema_name": "Custom app development",
        "topic": "custom apps",
        "blurb": "A product for customers or a tool for the team, on iPhone and in the browser.",
    },
]
